version: '3.8'

services:
  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db
    container_name: marketplace-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace-backend
    ports:
      - '8888:8888'
    environment:
      PORT: 8888
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  db_data: